services:

  backend:
    build: ./backend
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    ports:
      - "8081:8081"
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:8081/health" ]
      interval: 1s
      timeout: 5s
      retries: 3
      start_period: 1s
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        VUE_APP_API_URL_ARG: "/api"
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1/" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped