name: Docker Project Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_push_to_docker_hub:
    name: Push Docker image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Backend to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: ./backend/
          push: true
          tags: ${{ secrets.DOCKER_USER }}/docker-project-backend:latest
      - name: Push Frontend to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: ./frontend/
          push: true
          tags: ${{ secrets.DOCKER_USER }}/docker-project-frontend:latest

  scan-images-using-trivy:
    needs: [ build_and_push_to_docker_hub ]
    name: Run Trivy to scan vulnerabilities
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Pull Backend image
        run: docker pull ${{ secrets.DOCKER_USER }}/docker-project-backend:latest
      - name: Scan Backend image
        uses: aquasecurity/trivy-action@0.30.0
        with:
          image-ref: ${{ secrets.DOCKER_USER }}/docker-project-backend:latest
          format: table
          severity: CRITICAL
          vuln-type: os,library
          exit-code: 1
          ignore-unfixed: true
      - name: Pull Backend image
        run: docker pull ${{ secrets.DOCKER_USER }}/docker-project-frontend:latest
      - name: Scan Frontend image
        uses: aquasecurity/trivy-action@0.30.0
        with:
          image-ref: ${{ secrets.DOCKER_USER }}/docker-project-frontend:latest
          format: table
          severity: CRITICAL
          vuln-type: os,library
          exit-code: 1
          ignore-unfixed: true

  run-with-docker-compose:
    needs: [ scan-images-using-trivy ]
    name: Push Docker image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build via Docker Compose
        uses: hoverkraft-tech/compose-action@v2.2.0